# Generated by Django 4.1.2 on 2023-01-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(default='', max_length=20, verbose_name='Vendor Name')),
                ('vendoremail', models.EmailField(max_length=50, verbose_name='Email')),
                ('vendorcontactno', models.IntegerField(default='', verbose_name='Contact No')),
                ('company_address', models.TextField()),
                ('vendorpassword', models.CharField(max_length=20, verbose_name='Password')),
                ('vendor_GST_no', models.IntegerField(verbose_name='Vendor GST No')),
            ],
        ),
    ]
