# Generated by Django 4.1.2 on 2023-01-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_vendorregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorregister',
            name='vendor_GST_no',
            field=models.CharField(max_length=50, verbose_name='Vendor GST No'),
        ),
    ]
